[tasks.format-rust]
command = "cargo"
args = ["fmt"]

[tasks.format-toml]
install_crate = "taplo"
command = "taplo"
args = ["format"]

[tasks.format]
dependencies = ["format-rust", "format-toml"]

[tasks.format-rust-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.format-toml-check]
install_crate = "taplo"
command = "taplo"
args = ["format", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--", "--deny=warnings"]

[tasks.test]
command = "cargo"
args = ["test", "--no-fail-fast"]

[tasks.each-feature]
install_crate = "cargo-hack"
command = "cargo"
args = ["hack", "check", "--each-feature", "--no-dev-deps"]

[tasks.all-features]
install_crate = "cargo-hack"
command = "cargo"
args = ["hack", "check", "--feature-powerset", "--no-dev-deps"]

[tasks.verify]
dependencies = [
  "format-rust-check",
  "format-toml-check",
  "clippy",
  "test",
  "each-feature",
  "all-features",
]

[tasks.default]
alias = "verify"
