[package]
name = "fixture_integrity"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "fixture_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
