[package]
name = "fixture"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
name = "fixture"

[dependencies]
hdk = { workspace = true }

fixture_integrity = { workspace = true }
fixture_types = { workspace = true }
